package com.chhanda.ai.presentation.ui.chat.components

/**
 * Parses raw LLM output to separate thinking process from the actual response.
 */
fun parseMessageContent(rawText: String): Pair<String?, String> {
    val cleanedText = rawText
        .replace(Regex("<turn\\|?>"), "")
        .replace(Regex("<\\|channel>thought"), "")
        .replace(Regex("<\\|channel>"), "")
        .replace(Regex("<start_of_turn>"), "")
        .replace(Regex("<end_of_turn>"), "")
        .replace("\ufeff", "")
        .replace("\uFEFF", "")
        .replace("[UTF-8]", "")
        .replace("(UTF-8)", "")
        .replace("UTF-8: ", "")
        .replace("\u00A0", " ")
        .trim()

    var thinkingText: String? = null
    var responseText = cleanedText

    val startRegex = """<(?:thought|think)[^>]*>""".toRegex(RegexOption.IGNORE_CASE)
    val endRegex = """</(?:thought|think)[^>]*>""".toRegex(RegexOption.IGNORE_CASE)

    val startMatch = startRegex.find(cleanedText)
    if (startMatch != null) {
        val startIdx = startMatch.range.first
        val endMatch = endRegex.find(cleanedText, startIdx)
        if (endMatch != null) {
            val endIdx = endMatch.range.first
            thinkingText = cleanedText.substring(startIdx + startMatch.value.length, endIdx).trim()
            responseText = (cleanedText.substring(0, startIdx) + cleanedText.substring(endIdx + endMatch.value.length)).trim()
        } else {
            thinkingText = cleanedText.substring(startIdx + startMatch.value.length).trim()
            responseText = cleanedText.substring(0, startIdx).trim()
        }
    }

    val thinkingMarkers = listOf("Thinking Process:", "Thought:")
    for (marker in thinkingMarkers) {
        val index = responseText.indexOf(marker)
        if (index != -1) {
            val endOfThinking = responseText.indexOf("\n\n", index)
            if (endOfThinking != -1) {
                if (thinkingText == null) {
                    thinkingText = responseText.substring(index + marker.length, endOfThinking).trim()
                }
                responseText = (responseText.substring(0, index) + responseText.substring(endOfThinking)).trim()
            } else {
                if (thinkingText == null) {
                    thinkingText = responseText.substring(index + marker.length).trim()
                }
                responseText = responseText.substring(0, index).trim()
            }
            break
        }
    }

    // Proactively clean up any remaining thinking tags inside the text
    val cleanupRegex = """</?(?:thought|think)[^>]*>""".toRegex(RegexOption.IGNORE_CASE)
    responseText = responseText.replace(cleanupRegex, "").trim()
    thinkingText = thinkingText?.replace(cleanupRegex, "")?.trim()

    // Remove all general HTML/XML tags (e.g. <retrieved_web_knowledge>, </retrieved_web_knowledge>, <context>, etc.)
    val genericTagRegex = """</?[a-zA-Z_][a-zA-Z0-9_\-:]*[^>]*>""".toRegex()
    responseText = responseText.replace(genericTagRegex, "").trim()
    
    return Pair(thinkingText, cleanLatexFormatting(responseText))
}


/**
 * Cleans LaTeX math formatting often generated by smaller local models.
 */
fun cleanLatexFormatting(text: String): String {
    var cleaned = text
    
    // 1. Unescape escaped dollar signs that are wrapping math (e.g. \$29^\circ\text{C}\$)
    cleaned = cleaned.replace(Regex("""\\\$(.*?)\\\$"""), "$$1$")
    
    // 2. Process inline math blocks $...$
    cleaned = cleaned.replace(Regex("""\$([^$\n]+)\$""")) { match ->
        var inner = match.groupValues[1]
        if (inner.contains("\\circ") || inner.contains("\\text") || inner.contains("\\%") || inner.matches(Regex("""^[0-9.:\s]+[a-zA-Z/%]*$"""))) {
            inner = inner.replace(Regex("""\^?\\circ"""), "°")
            inner = inner.replace(Regex("""\\text\{([^}]+)\}"""), "$1")
            inner = inner.replace(Regex("""\\%"""), "%")
            inner.trim()
        } else {
            match.value
        }
    }
    
    // 3. Fallback: clean any remaining \circ, \text, \% outside blocks
    cleaned = cleaned.replace(Regex("""\^?\\circ"""), "°")
    cleaned = cleaned.replace(Regex("""\\text\{([^}]+)\}"""), "$1")
    cleaned = cleaned.replace(Regex("""\\%"""), "%")
    
    return cleaned
}


/**
 * Strips markdown and special tags for Text-to-Speech engines.
 */
fun cleanTextForTts(text: String): String {
    var cleaned = text
    
    // Strip trailing [Sources: ...] or [Source 1: ...] metadata blocks
    cleaned = cleaned.replace(Regex("(?i)\\[Sources?:?\\s*[\\s\\S]*?\\]"), "")
    
    // Strip inline citations like [Source #1], [Source 1], [1], (Source 1), (1)
    cleaned = cleaned.replace(Regex("(?i)\\[Source\\s*#?\\d+\\]"), "")
    cleaned = cleaned.replace(Regex("(?i)\\bSource\\s*#?\\d+\\b"), "")
    cleaned = cleaned.replace(Regex("\\[\\d+\\]"), "")
    cleaned = cleaned.replace(Regex("\\(\\d+\\)"), "")

    // Strip spoken inline citations (e.g., "according to source 1", "source one", "source #1", "source 2")
    cleaned = cleaned.replace(Regex("(?i)\\baccording to sources?\\s*(?:#?\\d+|one|two|three|four|five)?\\b"), "")
    cleaned = cleaned.replace(Regex("(?i)\\bsources?\\s*(?:#?\\d+|one|two|three|four|five|\\d+)\\b"), "")
    
    // Strip bullet-point prefixes like "Source 1:" or "Source 2 -"
    cleaned = cleaned.replace(Regex("(?i)\\bSource\\s*\\d+\\s*[:\\-–—]?\\s*"), "")
    cleaned = cleaned.replace(Regex("(?i)\\bSource\\s*(?:one|two|three|four|five)\\s*[:\\-–—]?\\s*"), "")
    
    // Clean up hanging punctuation resulting from stripped citations
    cleaned = cleaned
        .replace(Regex(",\\s*\\."), ".")
        .replace(Regex(",\\s*,"), ",")
        .replace(Regex("\\.\\s*\\."), ".")
    
    // Senior Pattern: Transform background file compiling actions into pleasant spoken notifications
    if (cleaned.contains("[GENERATE_FILE") || cleaned.contains("[CREATE_FILE")) {
        cleaned = cleaned.replace(Regex("\\[GENERATE_FILE.*?\\][\\s\\S]*?\\[/GENERATE_FILE\\]"), " [I have generated the requested document for you. You can download it directly from the chat bubble.] ")
        cleaned = cleaned.replace(Regex("\\[CREATE_FILE.*?\\][\\s\\S]*?\\[/CREATE_FILE\\]"), " [I have created the requested file for you. You can find it in the chat bubble.] ")
    }

    return cleaned
        .replace(Regex("\\*\\*(.*?)\\*\\*"), "$1")
        .replace(Regex("\\*(.*?)\\*"), "$1")
        .replace(Regex("`(.*?)`"), "$1")
        .replace(Regex("```[\\s\\S]*?```"), " I have written a code block here for your reference. ")
        .replace(Regex("#+\\s+"), "")
        .replace(Regex("\\[(.*?)\\]\\(.*?\\)"), "$1")
        .replace(Regex("[_~>]"), " ")
        // Convert Markdown bullets into conversational pauses
        .replace(Regex("^\\s*[-*+]\\s+"), ". ")
        .replace(Regex("\\n\\s*[-*+]\\s+"), ". ")
        // Convert numbered list prefixes into natural conversational pauses
        .replace(Regex("^\\s*\\d+\\.\\s+"), ". ")
        .replace(Regex("\\n\\s*\\d+\\.\\s+"), ". ")
        // Clean up brackets inserted for file text framing
        .replace("[", "")
        .replace("]", "")
        .replace(Regex("\\s+"), " ")
        .trim()
}
