package com.chhanda.ai.util

object Localization {
    private val translations = mapOf(
        "English" to mapOf(
            "dashboard" to "Home",
            "models" to "Models",
            "config" to "Config",
            "logs" to "Logs",
            "ram" to "RAM",
            "vram" to "VRAM",
            "tps" to "TOKENS/S",
            "devices" to "DEVICES",
            "connected" to "Connected",
            "active_model" to "Active Model",
            "no_active_model" to "No Active Model",
            "stopped" to "Stopped",
            "loading" to "Loading...",
            "chat_hint" to "Ask Chhanda...",
            "language" to "App Language",
            "restart_required" to "Restart Required",
            "restart_msg" to "Please restart the app to apply language settings.",
            "vpn_warning" to "VPN/Ad-guard detected. This may block local devices.",
            "internal_models" to "Internal Models",
            "shared_models" to "Shared Models",
            "downloadable_models" to "Downloadable Models",
            "secure_badge" to "SECURE",
            "detected_badge" to "DETECTED",
            "refresh" to "Refresh",
            "import" to "Import",
            "appearance" to "Appearance",
            "network_settings" to "Network Settings",
            "security" to "Security",
            "dark_mode" to "Dark Mode",
            "dark_mode_desc" to "Switch between light and dark themes.",
            "server_port" to "Server Port",
            "context_length" to "Context Length",
            "context_length_desc" to "Total tokens for processing.",
            "public_url" to "Public URL",
            "public_url_desc" to "Provide Ngrok or tunnel URL.",
            "max_devices" to "Max Devices",
            "max_devices_desc" to "Limit remote connections.",
            "api_key" to "API Key",
            "api_key_desc" to "For external integrations.",
            "hf_token" to "HuggingFace Token",
            "hf_token_desc" to "For gated models.",
            "save_changes" to "Save Changes",
            "generate_new" to "Generate New",
            "save_key" to "Save Key",
            "memory" to "Memory",
            "data_management" to "DATA MANAGEMENT",
            "data_ingestion" to "Data Ingestion",
            "upload_rag" to "Upload RAG Data",
            "upload_desc" to "Upload PDFs or images to train your local database.",
            "browse_files" to "Browse Files",
            "stats" to "Statistics",
            "storage_metrics" to "Storage Metrics",
            "total_indexed" to "Total Indexed",
            "files" to "files",
            "vector_storage" to "VECTOR STORAGE",
            "recent_uploads" to "Recent Uploads",
            "wipe_memory" to "Wipe All Local Memory",
            "used" to "Used",
            "search_hint" to "Search activity, LLM or status...",
            "all_logs" to "All Logs",
            "export" to "Export",
            "live_feed" to "LIVE FEED",
            "live_badge" to "LIVE",
            "thinking_process" to "Thinking Process",
            "active" to "ACTIVE",
            "ready" to "READY",
            "recommended" to "RECOMMENDED",
            "size" to "SIZE",
            "downloading" to "downloading...",
            "paused" to "paused",
            "downloaded" to "downloaded",
            "no_downloaded_models" to "No downloaded models",
            "global_connectivity" to "Global Connectivity",
            "storage_management" to "Storage Management",
            "ssh_tunnel" to "Global SSH Tunnel",
            "ssh_tunnel_desc_active" to "Global access enabled via secure SSH.",
            "ssh_tunnel_desc_inactive" to "Bypass router firewalls with a public URL.",
            "manage_chat_history" to "Manage Chat History",
            "manage_chat_history_desc" to "View and purge history across all connected devices.",
            "open" to "Open",
            "clear_history_title" to "Clear Local History?",
            "clear_history_text" to "This will permanently delete all chat history for this device. This action cannot be undone.",
            "purge_history_title" to "Purge All History?",
            "purge_history_text" to "This action will permanently delete all chat messages and local AI memory from this device. This cannot be undone.",
            "confirm_purge" to "CONFIRM PURGE",
            "vpn_warning" to "VPN Active: Try switching IPs below if connection fails.",
            "connection_gateway" to "Connection Gateway",
            "start_server" to "Start Server",
            "stop_server" to "Stop Server",
            "try_it" to "Try It",
            "clear_history" to "Clear History",
            "copy" to "Copy",
            "share" to "Share",
            "delete" to "Delete",
            "cancel" to "Cancel",
            "clear_logs_confirm" to "Clear all logs?",
            "clear_logs_desc" to "This will permanently remove all activity logs. This cannot be undone.",
            "confirm" to "Confirm",
            "delete_model_confirm" to "Delete Model?",
            "delete_model_desc" to "This will remove the model file from your device. You will need to download it again to use it."
        ),
        "Bengali" to mapOf(
            "dashboard" to "মূল পাতা",
            "models" to "মডেল",
            "config" to "সেটিংস",
            "logs" to "লগ",
            "ram" to "র‍্যাম",
            "vram" to "ভি-র‍্যাম",
            "tps" to "টোকেন/সেকেন্ড",
            "devices" to "ডিভাইস",
            "connected" to "সংযুক্ত",
            "active_model" to "সক্রিয় মডেল",
            "no_active_model" to "কোনো সক্রিয় মডেল নেই",
            "stopped" to "বন্ধ",
            "loading" to "লোড হচ্ছে...",
            "chat_hint" to "ছন্দ-কে জিজ্ঞাসা করুন...",
            "language" to "অ্যাপের ভাষা",
            "restart_required" to "পুনরায় চালু করা প্রয়োজন",
            "restart_msg" to "নতুন ভাষা সেটিংস প্রয়োগ করতে দয়া করে অ্যাপটি পুনরায় চালু করুন।",
            "vpn_warning" to "VPN সনাক্ত করা হয়েছে। এটি সংযোগে বাধা দিতে পারে।",
            "internal_models" to "অভ্যন্তরীণ মডেল",
            "shared_models" to "শেয়ার করা মডেল",
            "downloadable_models" to "ডাউনলোডযোগ্য মডেল",
            "secure_badge" to "সুরক্ষিত",
            "detected_badge" to "সনাক্ত করা হয়েছে",
            "refresh" to "রিফ্রেশ",
            "import" to "ইম্পোর্ট",
            "appearance" to "চেহারা",
            "network_settings" to "নেটওয়ার্ক সেটিংস",
            "security" to "নিরাপত্তা",
            "dark_mode" to "ডার্ক মোড",
            "dark_mode_desc" to "লাইট এবং ডার্ক থিমের মধ্যে পরিবর্তন করুন।",
            "server_port" to "সার্ভার পোর্ট",
            "context_length" to "কনটেক্সট দৈর্ঘ্য",
            "context_length_desc" to "প্রক্রিয়াকরণের জন্য মোট টোকেন।",
            "public_url" to "পাবলিক URL",
            "public_url_desc" to "Ngrok বা টানেল URL প্রদান করুন।",
            "max_devices" to "সর্বোচ্চ ডিভাইস",
            "max_devices_desc" to "রিমোট সংযোগ সীমিত করুন।",
            "api_key" to "API কী",
            "api_key_desc" to "বাহ্যিক ইন্টিগ্রেশনের জন্য।",
            "hf_token" to "HuggingFace টোকেন",
            "hf_token_desc" to "সুরক্ষিত মডেলের জন্য।",
            "save_changes" to "পরিবর্তনগুলি সংরক্ষণ করুন",
            "generate_new" to "নতুন তৈরি করুন",
            "save_key" to "কী সংরক্ষণ করুন",
            "memory" to "মেমোরি",
            "data_management" to "ডেটা ম্যানেজমেন্ট",
            "data_ingestion" to "ডেটা ইনজেশন",
            "upload_rag" to "RAG ডেটা আপলোড করুন",
            "upload_desc" to "আপনার ডাটাবেস প্রশিক্ষিত করতে PDF বা ছবি আপলোড করুন।",
            "browse_files" to "ফাইল খুঁজুন",
            "stats" to "পরিসংখ্যান",
            "storage_metrics" to "স্টোরেজ ম্যাট্রিক্স",
            "total_indexed" to "মোট ইনডেক্স করা",
            "files" to "ফাইল",
            "vector_storage" to "ভেক্টর স্টোরেজ",
            "recent_uploads" to "সাম্প্রতিক আপলোড",
            "wipe_memory" to "সব লোকাল মেমোরি মুছে ফেলুন",
            "used" to "ব্যবহৃত",
            "search_hint" to "অ্যাক্টিভিটি, LLM বা স্ট্যাটাস খুঁজুন...",
            "all_logs" to "সব লগ",
            "export" to "এক্সপোর্ট",
            "live_feed" to "লাইভ ফিড",
            "live_badge" to "লাইভ",
            "thinking_process" to "চিন্তাভাবনা প্রক্রিয়া",
            "active" to "সক্রিয়",
            "ready" to "প্রস্তুত",
            "recommended" to "সুপারিশকৃত",
            "size" to "সাইজ",
            "downloading" to "ডাউনলোড হচ্ছে...",
            "paused" to "স্থগিত",
            "downloaded" to "ডাউনলোড সম্পন্ন",
            "no_downloaded_models" to "কোনো ডাউনলোড করা মডেল নেই",
            "global_connectivity" to "গ্লোবাল কানেক্টিভিটি",
            "storage_management" to "স্টোরেজ ম্যানেজমেন্ট",
            "ssh_tunnel" to "গ্লোবাল SSH টানেল",
            "ssh_tunnel_desc_active" to "সুরক্ষিত SSH এর মাধ্যমে গ্লোবাল অ্যাক্সেস সক্ষম করা হয়েছে।",
            "ssh_tunnel_desc_inactive" to "পাবলিক URL এর মাধ্যমে রাউটার ফায়ারওয়াল বাইপাস করুন।",
            "manage_chat_history" to "চ্যাট ইতিহাস পরিচালনা করুন",
            "manage_chat_history_desc" to "সব সংযুক্ত ডিভাইসে ইতিহাস দেখুন এবং মুছে ফেলুন।",
            "open" to "খুলুন",
            "clear_history_title" to "লোকাল ইতিহাস মুছে ফেলবেন?",
            "clear_history_text" to "এটি এই ডিভাইসের সব চ্যাট ইতিহাস স্থায়ীভাবে মুছে ফেলবে। এটি আর ফিরে পাওয়া সম্ভব নয়।",
            "purge_history_title" to "সব ইতিহাস মুছে ফেলবেন?",
            "purge_history_text" to "এটি এই ডিভাইসের সব চ্যাট মেসেজ এবং লোকাল AI মেমোরি স্থায়ীভাবে মুছে ফেলবে। এটি আর ফিরে পাওয়া সম্ভব নয়।",
            "confirm_purge" to "মুছে ফেলা নিশ্চিত করুন",
            "vpn_warning" to "VPN সক্রিয়: সংযোগ ব্যর্থ হলে নিচের IP পরিবর্তনের চেষ্টা করুন।",
            "connection_gateway" to "কানেকশন গেটওয়ে",
            "start_server" to "সার্ভার চালু করুন",
            "stop_server" to "সার্ভার বন্ধ করুন",
            "try_it" to "চেষ্টা করুন",
            "clear_history" to "ইতিহাস মুছুন",
            "copy" to "কপি",
            "share" to "শেয়ার",
            "delete" to "মুছুন",
            "cancel" to "বাতিল",
            "clear_logs_confirm" to "সব লগ মুছে ফেলবেন?",
            "clear_logs_desc" to "এটি সব অ্যাক্টিভিটি লগ স্থায়ীভাবে মুছে ফেলবে। এটি আর ফিরে পাওয়া সম্ভব নয়।",
            "confirm" to "নিশ্চিত করুন",
            "delete_model_confirm" to "মডেল মুছে ফেলবেন?",
            "delete_model_desc" to "এটি আপনার ডিভাইস থেকে মডেল ফাইলটি মুছে ফেলবে। এটি ব্যবহার করতে আপনাকে আবার ডাউনলোড করতে হবে।"
        ),
        "Hindi" to mapOf(
            "dashboard" to "मुख्य",
            "models" to "मॉडल",
            "config" to "सेटिंग्स",
            "logs" to "लॉग",
            "ram" to "रैम",
            "vram" to "वी-रैम",
            "tps" to "टोकन/सेकंड",
            "devices" to "उपकरण",
            "connected" to "जुड़ा हुआ",
            "active_model" to "सक्रिय मॉडल",
            "no_active_model" to "कोई सक्रिय मॉडल नहीं",
            "stopped" to "रुका हुआ",
            "loading" to "लोड हो रहा है...",
            "chat_hint" to "छंदा से पूछें...",
            "language" to "ऐप की भाषा",
            "restart_required" to "पुनरारंभ आवश्यक",
            "restart_msg" to "भाषा सेटिंग्स लागू करने के लिए कृपया ऐप को पुनरारंभ करें।",
            "vpn_warning" to "VPN का पता चला। यह कनेक्शन बाधित कर सकता है।",
            "internal_models" to "आंतरिक मॉडल",
            "shared_models" to "साझा मॉडल",
            "downloadable_models" to "डाउनलोड करने योग्य मॉडल",
            "secure_badge" to "सुरक्षित",
            "detected_badge" to "पता चला",
            "refresh" to "रीफ्रेश",
            "import" to "इंपोर्ट",
            "appearance" to "दिखावट",
            "network_settings" to "नेटवर्क सेटिंग्स",
            "security" to "सुरक्षा",
            "dark_mode" to "डार्क मोड",
            "dark_mode_desc" to "लाइट और डार्क थीम के बीच स्विच करें।",
            "server_port" to "सर्वर पोर्ट",
            "context_length" to "संदर्भ लंबाई",
            "context_length_desc" to "प्रसंस्करण के लिए कुल टोकन।",
            "public_url" to "सार्वजनिक URL",
            "public_url_desc" to "Ngrok या टनल URL प्रदान करें।",
            "max_devices" to "अधिकतम उपकरण",
            "max_devices_desc" to "रिमोट कनेक्शन सीमित करें।",
            "api_key" to "API कुंजी",
            "api_key_desc" to "बाहरी एकीकरण के लिए।",
            "hf_token" to "HuggingFace टोकन",
            "hf_token_desc" to "गैटेड मॉडल के लिए।",
            "save_changes" to "परिवर्तन सहेजें",
            "generate_new" to "नया बनाएं",
            "save_key" to "कुंजी सहेजें",
            "memory" to "मेमोरी",
            "data_management" to "डेटा प्रबंधन",
            "data_ingestion" to "डेटा अंतर्ग्रहण",
            "upload_rag" to "RAG डेटा अपलोड करें",
            "upload_desc" to "डेटाबेस को प्रशिक्षित करने के लिए PDF या चित्र अपलोड करें।",
            "browse_files" to "फ़ाइलें ब्राउज़ करें",
            "stats" to "सांख्यिकी",
            "storage_metrics" to "स्टोरेज मेट्रिक्स",
            "total_indexed" to "कुल अनुक्रमित",
            "files" to "फ़ाइलें",
            "vector_storage" to "वेक्टर स्टोरेज",
            "recent_uploads" to "हाल के अपलोड",
            "wipe_memory" to "सभी स्थानीय मेमोरी मिटाएं",
            "used" to "उपयोग किया गया",
            "search_hint" to "गतिविधि, LLM या स्थिति खोजें...",
            "all_logs" to "सभी लॉग",
            "export" to "एक्सपोर्ट",
            "live_feed" to "लाइव फीड",
            "live_badge" to "लाइव",
            "thinking_process" to "सोचने की प्रक्रिया",
            "active" to "सक्रिय",
            "ready" to "तैयार",
            "recommended" to "अनुशंसित",
            "size" to "आकार",
            "downloading" to "डाउनलोड हो रहा है...",
            "paused" to "रुका हुआ",
            "downloaded" to "डाउनलोड हो गया",
            "no_downloaded_models" to "कोई डाउनलोड किया गया मॉडल नहीं",
            "global_connectivity" to "वैश्विक कनेक्टिविटी",
            "storage_management" to "स्टोरेज प्रबंधन",
            "ssh_tunnel" to "वैश्विक SSH टनल",
            "ssh_tunnel_desc_active" to "सुरक्षित SSH के माध्यम से वैश्विक पहुंच सक्षम है।",
            "ssh_tunnel_desc_inactive" to "पब्लिक URL के साथ राउटर फ़ायरवॉल को बायपास करें।",
            "manage_chat_history" to "चैट इतिहास प्रबंधित करें",
            "manage_chat_history_desc" to "सभी जुड़े उपकरणों पर इतिहास देखें और साफ़ करें।",
            "open" to "खोलें",
            "clear_history_title" to "स्थानीय इतिहास मिटाएं?",
            "clear_history_text" to "यह स्थायी रूप से इस डिवाइस के सभी चैट इतिहास को हटा देगा। यह क्रिया पूर्ववत नहीं की जा सकती।",
            "purge_history_title" to "सभी इतिहास मिटाएं?",
            "purge_history_text" to "यह क्रिया स्थायी रूप से इस डिवाइस से सभी चैट संदेशों और स्थानीय AI मेमोरी को हटा देगी। इसे पूर्ववत नहीं किया जा सकता है।",
            "confirm_purge" to "मिटाना सुनिश्चित करें",
            "vpn_warning" to "VPN सक्रिय: यदि कनेक्शन विफल हो जाता है तो नीचे IP बदलने का प्रयास करें।",
            "connection_gateway" to "कनेक्शन गेटवे",
            "start_server" to "सर्वर शुरू करें",
            "stop_server" to "सर्वर बंद करें",
            "try_it" to "कोशिश करें",
            "clear_history" to "इतिहास साफ़ करें",
            "copy" to "कॉपी",
            "share" to "शेयर",
            "delete" to "हटाएं",
            "cancel" to "रद्द करें",
            "clear_logs_confirm" to "सभी लॉग मिटाएं?",
            "clear_logs_desc" to "यह सभी गतिविधि लॉग स्थायी रूप से हटा देगा। इसे पूर्ववत नहीं किया जा सकता है।",
            "confirm" to "पुष्टि करें",
            "delete_model_confirm" to "मॉडल हटाएं?",
            "delete_model_desc" to "यह आपके डिवाइस से मॉडल फ़ाइल को हटा देगा। इसका उपयोग करने के लिए आपको इसे फिर से डाउनलोड करना होगा।"
        ),
        "Spanish" to mapOf(
            "dashboard" to "Inicio",
            "models" to "Modelos",
            "config" to "Config",
            "logs" to "Logs",
            "ram" to "RAM",
            "vram" to "VRAM",
            "tps" to "TOKENS/S",
            "devices" to "DISPOSITIVOS",
            "connected" to "Conectado",
            "active_model" to "Modelo Activo",
            "no_active_model" to "Sin Modelo Activo",
            "stopped" to "Detenido",
            "loading" to "Cargando...",
            "chat_hint" to "Pregunta a Chhanda...",
            "language" to "Idioma de la aplicación",
            "restart_required" to "Reinicio Necesario",
            "restart_msg" to "Reinicie la aplicación para aplicar los nuevos ajustes de idioma.",
            "vpn_warning" to "VPN detectada. Esto puede bloquear dispositivos locales.",
            "internal_models" to "Modelos Internos",
            "shared_models" to "Modelos Compartidos",
            "downloadable_models" to "Modelos Descargables",
            "secure_badge" to "SEGURO",
            "detected_badge" to "DETECTADO",
            "refresh" to "Refrescar",
            "import" to "Importar",
            "appearance" to "Apariencia",
            "network_settings" to "Ajustes de Red",
            "security" to "Seguridad",
            "dark_mode" to "Modo Oscuro",
            "dark_mode_desc" to "Cambiar entre temas claros y oscuros.",
            "server_port" to "Puerto del Servidor",
            "context_length" to "Longitud del Contexto",
            "context_length_desc" to "Tokens totales para procesamiento.",
            "public_url" to "URL Pública",
            "public_url_desc" to "URL de Ngrok o túnel.",
            "max_devices" to "Máximo de Dispositivos",
            "max_devices_desc" to "Limitar conexiones remotas.",
            "api_key" to "Clave API",
            "api_key_desc" to "Para integraciones externas.",
            "hf_token" to "Token de HuggingFace",
            "hf_token_desc" to "Para modelos restringidos.",
            "save_changes" to "Guardar Cambios",
            "generate_new" to "Generar Nuevo",
            "save_key" to "Guardar Clave",
            "memory" to "Memoria",
            "data_management" to "GESTIÓN DE DATOS",
            "data_ingestion" to "Ingestión de Datos",
            "upload_rag" to "Subir Datos RAG",
            "upload_desc" to "Suba PDFs o imágenes para entrenar su base de datos.",
            "browse_files" to "Buscar Archivos",
            "stats" to "Estadísticas",
            "storage_metrics" to "Métricas de Almacenamiento",
            "total_indexed" to "Total Indexado",
            "files" to "archivos",
            "vector_storage" to "ALMACENAMIENTO VECTORIAL",
            "recent_uploads" to "Subidas Recientes",
            "wipe_memory" to "Borrar Toda la Memoria Local",
            "used" to "Usado",
            "search_hint" to "Buscar actividad, LLM o estado...",
            "all_logs" to "Todos los Registros",
            "export" to "Exportar",
            "live_feed" to "FEED EN VIVO",
            "live_badge" to "VIVO",
            "thinking_process" to "Proceso de Pensamiento",
            "active" to "ACTIVO",
            "ready" to "LISTO",
            "recommended" to "RECOMENDADO",
            "size" to "TAMAÑO",
            "downloading" to "descargando...",
            "paused" to "pausado",
            "downloaded" to "descargado",
            "no_downloaded_models" to "Sin modelos descargados",
            "global_connectivity" to "Conectividad Global",
            "storage_management" to "Gestión de Almacenamiento",
            "ssh_tunnel" to "Túnel SSH Global",
            "ssh_tunnel_desc_active" to "Acceso global habilitado vía SSH seguro.",
            "ssh_tunnel_desc_inactive" to "Evite firewalls de router con una URL pública.",
            "manage_chat_history" to "Gestionar Historial de Chat",
            "manage_chat_history_desc" to "Vea y purgue el historial en todos los dispositivos.",
            "open" to "Abrir",
            "clear_history_title" to "¿Borrar Historial Local?",
            "clear_history_text" to "Esto eliminará permanentemente todo el historial de chat de este dispositivo. Esta acción no se puede deshacer.",
            "purge_history_title" to "¿Purgar Todo el Historial?",
            "purge_history_text" to "Esta acción eliminará permanentemente todos los mensajes de chat y la memoria de IA local de este dispositivo. No se puede deshacer.",
            "confirm_purge" to "CONFIRMAR PURGA",
            "vpn_warning" to "VPN Activa: Intente cambiar las IPs a continuación si falla la conexión.",
            "connection_gateway" to "Pasarela de Conexión",
            "start_server" to "Iniciar Servidor",
            "stop_server" to "Detener Servidor",
            "try_it" to "Probar",
            "clear_history" to "Borrar Historial",
            "copy" to "Copiar",
            "share" to "Compartir",
            "delete" to "Eliminar",
            "cancel" to "Cancelar",
            "clear_logs_confirm" to "¿Borrar todos los registros?",
            "clear_logs_desc" to "Esto eliminará permanentemente todos los registros de actividad. Esta acción no se puede deshacer.",
            "confirm" to "Confirmar",
            "delete_model_confirm" to "¿Eliminar modelo?",
            "delete_model_desc" to "Esto eliminará el archivo del modelo de su dispositivo. Tendrá que descargarlo de nuevo para usarlo."
        )
    )

    fun getString(key: String, language: String): String {
        return translations[language]?.get(key) ?: translations["English"]?.get(key) ?: key
    }

    val supportedLanguages = translations.keys.toList().sorted()
}
